// default package
// Generated Jul 11, 2013 4:54:55 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Class generated by hbm2java
 */
public class Class implements java.io.Serializable {

	private Integer classId;
	private String title;
	private String semester;
	private Set studentClasses = new HashSet(0);

	public Class() {
	}

	public Class(String title, String semester) {
		this.title = title;
		this.semester = semester;
	}

	public Class(String title, String semester, Set studentClasses) {
		this.title = title;
		this.semester = semester;
		this.studentClasses = studentClasses;
	}

	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSemester() {
		return this.semester;
	}

	public void setSemester(String semester) {
		this.semester = semester;
	}

	public Set getStudentClasses() {
		return this.studentClasses;
	}

	public void setStudentClasses(Set studentClasses) {
		this.studentClasses = studentClasses;
	}

}
