// default package
// Generated Jul 11, 2013 4:54:55 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer studentId;
	private String studentName;
	private String studentAge;
	private Set studentClasses = new HashSet(0);
	private StudentInformation studentInformation;
	private Set projectses = new HashSet(0);

	public Student() {
	}

	public Student(String studentName, String studentAge) {
		this.studentName = studentName;
		this.studentAge = studentAge;
	}

	public Student(String studentName, String studentAge, Set studentClasses,
			StudentInformation studentInformation, Set projectses) {
		this.studentName = studentName;
		this.studentAge = studentAge;
		this.studentClasses = studentClasses;
		this.studentInformation = studentInformation;
		this.projectses = projectses;
	}

	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	public String getStudentAge() {
		return this.studentAge;
	}

	public void setStudentAge(String studentAge) {
		this.studentAge = studentAge;
	}

	public Set getStudentClasses() {
		return this.studentClasses;
	}

	public void setStudentClasses(Set studentClasses) {
		this.studentClasses = studentClasses;
	}

	public StudentInformation getStudentInformation() {
		return this.studentInformation;
	}

	public void setStudentInformation(StudentInformation studentInformation) {
		this.studentInformation = studentInformation;
	}

	public Set getProjectses() {
		return this.projectses;
	}

	public void setProjectses(Set projectses) {
		this.projectses = projectses;
	}

}
