// default package
// Generated Jul 11, 2013 4:54:55 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * StudentClass generated by hbm2java
 */
public class StudentClass  implements java.io.Serializable {


     private StudentClassId id;
     private Class class;
     private Student student;
     private Date registered;

    public StudentClass() {
    }

    public StudentClass(StudentClassId id, Class class, Student student, Date registered) {
       this.id = id;
       this.class = class;
       this.student = student;
       this.registered = registered;
    }
   
    public StudentClassId getId() {
        return this.id;
    }
    
    public void setId(StudentClassId id) {
        this.id = id;
    }
    public Class getClass() {
        return this.class;
    }
    
    public void setClass(Class class) {
        this.class = class;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Date getRegistered() {
        return this.registered;
    }
    
    public void setRegistered(Date registered) {
        this.registered = registered;
    }




}


