// default package
// Generated Jul 11, 2013 4:54:55 PM by Hibernate Tools 4.0.0

/**
 * StudentClassId generated by hbm2java
 */
public class StudentClassId implements java.io.Serializable {

	private int idStudent;
	private int classId;

	public StudentClassId() {
	}

	public StudentClassId(int idStudent, int classId) {
		this.idStudent = idStudent;
		this.classId = classId;
	}

	public int getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(int idStudent) {
		this.idStudent = idStudent;
	}

	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentClassId))
			return false;
		StudentClassId castOther = (StudentClassId) other;

		return (this.getIdStudent() == castOther.getIdStudent())
				&& (this.getClassId() == castOther.getClassId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdStudent();
		result = 37 * result + this.getClassId();
		return result;
	}

}
