package hibernateconfig;
// Generated Aug 13, 2019 9:59:22 PM by Hibernate Tools 5.4.2.Final

/**
 * FilmText generated by hbm2java
 */
public class FilmText implements java.io.Serializable {

	private Short filmId;
	private String title;
	private String description;

	public FilmText() {
	}

	public FilmText(String title) {
		this.title = title;
	}

	public FilmText(String title, String description) {
		this.title = title;
		this.description = description;
	}

	public Short getFilmId() {
		return this.filmId;
	}

	public void setFilmId(Short filmId) {
		this.filmId = filmId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
