package hibernateconfig;
// Generated Aug 13, 2019 9:59:22 PM by Hibernate Tools 5.4.2.Final

/**
 * StaffList generated by hbm2java
 */
public class StaffList implements java.io.Serializable {

	private StaffListId id;

	public StaffList() {
	}

	public StaffList(StaffListId id) {
		this.id = id;
	}

	public StaffListId getId() {
		return this.id;
	}

	public void setId(StaffListId id) {
		this.id = id;
	}

}
